var numbera = []
function cosmetics(self){
document.write( '  <table>')
document.write( '    <tr>')
document.write( '      <th>'+numbera[0]+'</th>')
document.write( '      <td>'+numbera[1]+'</td>')
document.write( '    </tr>')
document.write( '    <tr>')
document.write( '    <th>'+numbera[2]+'</th>')
document.write( '      <td>'+numbera[3]+'</td>')
document.write( '    </tr>')
document.write( '    <tr>')
document.write( '      <th>'+numbera[4]+'</th>')
document.write( '      <td>'+numbera[5]+'</td>')
document.write( '    </tr>')
document.write( '    <tr>')
document.write( '      <th>'+numbera[6]+'</th>')
document.write( '      <td>  <audio controls>')
document.write( '          <source src=".mp3" type="audio/mp3">')
document.write( '          </audio></td>')
document.write( '    </tr>')
document.write( '  </table>')
};
