var numbera = ['日本語表現','一 二 三 四 五 六 七 八 九 十','韓国表現','일 이 삼 사 오 육 칠 팔 구 십','発音','il i sam sa o yug chil pal gu sib','録音']
var numberbb = ['日本語表現','一つ　二つ　三つ　四つ　五つ　六つ　七つ　八つ　九つ　十 ','韓国表現','하나   둘   셋   넷   다섯   여섯   일곱   여덣   아홉   열','発音','hana   dul   ses   nes   daseos   yeoseos   ilgob   yeodeolh   ahob   yeol','録音']
function numbers(self){
document.write( '  <table>')
document.write( '    <tr>')
document.write( '      <th>'+numbera[0]+'</th>')
document.write( '      <td>'+numbera[1]+'</td>')
document.write( '    </tr>')
document.write( '    <tr>')
document.write( '    <th>'+numbera[2]+'</th>')
document.write( '      <td>'+numbera[3]+'</td>')
document.write( '    </tr>')
document.write( '    <tr>')
document.write( '      <th>'+numbera[4]+'</th>')
document.write( '      <td>'+numbera[5]+'</td>')
document.write( '    </tr>')
document.write( '    <tr>')
document.write( '      <th>'+numbera[6]+'</th>')
document.write( '      <td>  <audio controls>')
document.write( '          <source src="数字.mp3" type="audio/mp3">')
document.write( '          </audio></td>')
document.write( '    </tr>')
document.write( '  </table>')
};

function numberb(self){
document.write( '  <table>')
document.write( '    <tr>')
document.write( '      <th>'+numberbb[0]+'</th>')
document.write( '      <td>'+numberbb[1]+'</td>')
document.write( '    </tr>')
document.write( '    <tr>')
document.write( '    <th>'+numberbb[2]+'</th>')
document.write( '      <td>'+numberbb[3]+'</td>')
document.write( '    </tr>')
document.write( '    <tr>')
document.write( '      <th>'+numberbb[4]+'</th>')
document.write( '      <td>'+numberbb[5]+'</td>')
document.write( '    </tr>')
document.write( '    <tr>')
document.write( '      <th>'+numberbb[6]+'</th>')
document.write( '      <td>  <audio controls>')
document.write( '          <source src="数字b.mp3" type="audio/mp3">')
document.write( '          </audio></td>')
document.write( '    </tr>')
document.write( '  </table>')
};
